/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package doanoop;

import com.formdev.flatlaf.FlatLightLaf;
import controller.DAO;
import doanoop.Dialog.Fix_TK;
import doanoop.Dialog.GiaoKhoa_Detail;
import doanoop.Dialog.GiaoKhoa_Dialog;
import doanoop.Dialog.GiaoTrinh_Detail;
import doanoop.Dialog.GiaoTrinh_Dialog;
import doanoop.Dialog.Truyen_Detail;
import doanoop.Dialog.Truyen_Dialog;
import doanoop.Panel.GiaoKhoa_Panel;
import doanoop.Panel.GiaoTrinh_Panel;
import doanoop.Panel.Truyen_Panel;
import doanoop.model.Book;
import doanoop.model.GiaoTrinh;
import doanoop.model.Sachgiaokhoa;
import doanoop.model.Truyen;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import static javax.management.remote.JMXConnectorFactory.connect;
import java.sql.*;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;


public class Product extends javax.swing.JFrame {
    GiaoTrinh_Panel gt;
    Truyen_Panel tr;
    GiaoKhoa_Panel gk;
    public ArrayList<Book> list;
    public ArrayList<GiaoTrinh> list_GT;
    public ArrayList<Truyen> list_TR;
    public ArrayList<Sachgiaokhoa>list_GK;
    DefaultTableModel model;
    public Product() {
        initComponents();
        setLocationRelativeTo(null);
       
        model = (DefaultTableModel) tbllist.getModel();
        model.setColumnIdentifiers(new Object[]{
            "Mã sách","Tên sách","Thể loại","Tác giả","Giá"
        });
        list = new DAO().getBookList();
        list_GT=new DAO().getGTBook();
        list_TR=new DAO().getTRBook();
        list_GK=new DAO().getGKBook();
      
        showTable();
    }   
    public void showTable() {
        
        for (Book book:list) {
            model.addRow(new Object[]{
             book.getMasach(),book.getTensach(),book.getTheloai(),book.getTacgia(),book.getGia()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMasach = new javax.swing.JTextField();
        txtTensach = new javax.swing.JTextField();
        txtTacgia = new javax.swing.JTextField();
        txtNXB = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtNamXB = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbxTheloai = new javax.swing.JComboBox<>();
        Panel_Theloai = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGia = new javax.swing.JTextField();
        btnThem = new javax.swing.JButton();
        btnNhaplai = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbllist = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        cbxSearch = new javax.swing.JComboBox<>();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(1130, 790));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Mã sách");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Tên sách");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Tác giả");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Nhà xuất bản");

        txtMasach.setBackground(new java.awt.Color(255, 51, 51));
        txtMasach.setForeground(new java.awt.Color(255, 255, 255));
        txtMasach.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtMasach.setCaretColor(new java.awt.Color(255, 255, 255));
        txtMasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMasachActionPerformed(evt);
            }
        });

        txtTensach.setBackground(new java.awt.Color(255, 51, 51));
        txtTensach.setForeground(new java.awt.Color(255, 255, 255));
        txtTensach.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtTensach.setCaretColor(new java.awt.Color(255, 255, 255));

        txtTacgia.setBackground(new java.awt.Color(255, 51, 51));
        txtTacgia.setForeground(new java.awt.Color(255, 255, 255));
        txtTacgia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtTacgia.setCaretColor(new java.awt.Color(255, 255, 255));

        txtNXB.setBackground(new java.awt.Color(255, 51, 51));
        txtNXB.setForeground(new java.awt.Color(255, 255, 255));
        txtNXB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNXB.setCaretColor(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Năm xuất bản");

        txtNamXB.setBackground(new java.awt.Color(255, 51, 51));
        txtNamXB.setForeground(new java.awt.Color(255, 255, 255));
        txtNamXB.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtNamXB.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNamXB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamXBKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Giá");

        cbxTheloai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn--", "Giáo trình", "Truyện", "Sách giáo khoa" }));
        cbxTheloai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTheloaiActionPerformed(evt);
            }
        });

        Panel_Theloai.setBackground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thể loại");

        txtGia.setBackground(new java.awt.Color(255, 51, 51));
        txtGia.setForeground(new java.awt.Color(255, 255, 255));
        txtGia.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        txtGia.setCaretColor(new java.awt.Color(255, 255, 255));
        txtGia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtGiaKeyTyped(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnNhaplai.setText("Nhập lại");

        tbllist.setBackground(java.awt.SystemColor.inactiveCaption);
        tbllist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbllist);

        jButton1.setText("Sửa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Xem chi tiết");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        cbxSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã sách", "Tên sách", "Tác giả" }));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Panel_Theloai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtMasach, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(7, 7, 7)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNamXB)
                                    .addComponent(txtTacgia)
                                    .addComponent(txtNXB)
                                    .addComponent(cbxTheloai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtTensach, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(51, 51, 51))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(cbxSearch, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNhaplai, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSearch))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtTensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtNamXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addComponent(Panel_Theloai, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(79, 79, 79)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnNhaplai))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 609, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
        );

        setBounds(0, 0, 964, 607);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

    }//GEN-LAST:event_btnLoginActionPerformed

    private void cbxTheloaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTheloaiActionPerformed
        switch ((String)cbxTheloai.getSelectedItem()){
            case "Giáo trình":
               gt =new GiaoTrinh_Panel();
               Panel_Theloai.removeAll();
               Panel_Theloai.add(gt);
               Panel_Theloai.validate();
               break;
            
            case "Truyện":
                tr=new Truyen_Panel();
                Panel_Theloai.removeAll();
                Panel_Theloai.add(tr);
                Panel_Theloai.validate();
                break;
            case "Sách giáo khoa":
                gk=new GiaoKhoa_Panel();
                Panel_Theloai.removeAll();
                Panel_Theloai.add(gk);
                Panel_Theloai.validate();
                break;
        }
        
    }//GEN-LAST:event_cbxTheloaiActionPerformed

    private void txtMasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMasachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMasachActionPerformed
    void valid(){
        if(txtMasach.getText().equals(""))JOptionPane.showMessageDialog(rootPane,"Điền vào Mã sách");
        else if(txtTensach.getText().equals(""))JOptionPane.showMessageDialog(rootPane,"Điền vào tên sách");
        else if (txtTacgia.getText().equals(""))JOptionPane.showMessageDialog(rootPane,"Điền vào tác giả");
        else if(txtNXB.getText().equals(""))JOptionPane.showMessageDialog(rootPane,"Điền vào Nhà xuất bản");
        else if(txtNamXB.getText().equals(""))JOptionPane.showMessageDialog(rootPane,"Điền vào Năm xuất bản");
        else if(txtGia.getText().equals(""))JOptionPane.showMessageDialog(rootPane,"Điền vào giá sách");
    }
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        valid();
        switch ((String)cbxTheloai.getSelectedItem()) {
            case "Giáo trình":
                GiaoTrinh gtr =new GiaoTrinh();
         gtr.setMasach(txtMasach.getText());
         gtr.setTensach(txtTensach.getText());
         gtr.setTacgia(txtTacgia.getText());
         gtr.setNhaxuatban(txtNXB.getText());
         gtr.setNamxuatban(Integer.parseInt(txtNamXB.getText()));
         gtr.setGia(Integer.parseInt(txtGia.getText()));
         gtr.setLinhvuc(gt.getLinhvuc());
         
        if(new DAO().addGT( gtr)){
            JOptionPane.showMessageDialog(this,"Success! ");
            list.add((Book)gtr);
            list_GT.add(gtr);
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Error!!!");
        }
                break;
            case "Truyện":
                Truyen truyen =new Truyen();
            truyen.setMasach(txtMasach.getText());
            truyen.setTensach(txtTensach.getText());
            truyen.setTacgia(txtTacgia.getText());
            truyen.setNhaxuatban(txtNXB.getText());
            truyen.setNamxuatban(Integer.parseInt(txtNamXB.getText()));
            truyen.setGia(Integer.parseInt(txtGia.getText()));
            truyen.setTomau(tr.Mau());
           if(new DAO().addTR( truyen)){
               JOptionPane.showMessageDialog(this,"Success!");
               list.add((Book)truyen);
               list_TR.add(truyen);
           }
           else{
               JOptionPane.showMessageDialog(this, "Error!!!");
           }
        
            case "Sách giáo khoa":
               Sachgiaokhoa sgk=new Sachgiaokhoa();
               sgk.setMasach(txtMasach.getText());
               sgk.setTensach(txtTensach.getText());
               sgk.setTacgia(txtTacgia.getText());
               sgk.setNhaxuatban(txtNXB.getText());
               sgk.setNamxuatban(Integer.parseInt(txtNamXB.getText()));
               sgk.setGia(Integer.parseInt(txtGia.getText()));
               sgk.setKhoi(gk.getKhoi());
               if(new DAO().addSGK(sgk)){
                   JOptionPane.showMessageDialog(rootPane,"Success!");
                   list.add((Book)sgk);
                   list_GK.add(sgk);
               }
               
        }
    }//GEN-LAST:event_btnThemActionPerformed
    int selectedIndex;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        selectedIndex=tbllist.getSelectedRow();
        if(list.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Danh sách rỗng");
        }
        else if(selectedIndex<0) JOptionPane.showMessageDialog(rootPane, "Hãy chọn 1 sách để sửa");
        else{
            switch(list.get(selectedIndex).getTheloai()){
                case "Giáo trình":
                    GiaoTrinh_Dialog gd=new GiaoTrinh_Dialog(this, rootPaneCheckingEnabled);
                gd.getData(list_GT.get(selectedIndex));
                gd.setVisible(true);
                break;
                case "Truyện":
                    Truyen_Dialog tr=new Truyen_Dialog(this, rootPaneCheckingEnabled);
                    tr.getData(list_TR.get(selectedIndex));
                    tr.setVisible(true);
                    break;
                case "Sách giáo khoa":
                    GiaoKhoa_Dialog gkd=new GiaoKhoa_Dialog(this, rootPaneCheckingEnabled);
                    gkd.getData(list_GK.get(selectedIndex));
                    gkd.setVisible(true);
                    break;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    selectedIndex=tbllist.getSelectedRow();
        if(list.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Danh sách rỗng");
        }
        else if(selectedIndex<0) JOptionPane.showMessageDialog(rootPane, "Hãy chọn 1 sách để xem chi tiết");
        else{
            switch(list.get(selectedIndex).getTheloai()){
                case "Giáo trình":
                    GiaoTrinh_Detail gd=new GiaoTrinh_Detail(this, rootPaneCheckingEnabled);
                gd.getData(list_GT.get(selectedIndex));
                gd.setVisible(true);
                break;
                case "Truyện":
                    Truyen_Detail tr=new Truyen_Detail(this, rootPaneCheckingEnabled);
                    tr.getData(list_TR.get(selectedIndex));
                    tr.setVisible(true);
                    break;
                case "Sách giáo khoa":
                    GiaoKhoa_Detail gkd =new GiaoKhoa_Detail(this, rootPaneCheckingEnabled);
                    gkd.getData(list_GK.get(selectedIndex));
                    gkd.setVisible(true);
                    break;
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtGiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGiaKeyTyped
            char c=evt.getKeyChar();
            if(!Character.isDigit(c))
                evt.consume();
    }//GEN-LAST:event_txtGiaKeyTyped

    private void txtNamXBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamXBKeyTyped
        char c=evt.getKeyChar();
            if(!Character.isDigit(c))
                evt.consume();
    }//GEN-LAST:event_txtNamXBKeyTyped

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        switch((String)cbxSearch.getSelectedItem()){
            case "Mã sách":
                model.setRowCount(0);
                for(Book book:new DAO().findByMasach(txtSearch.getText())){
                    model.addRow(new Object[]{
                        book.getMasach(),book.getTensach(),book.getTheloai(),book.getTacgia(),book.getGia()
                    });
                }
                break;
            case "Tên sách":
                model.setRowCount(0);
                for(Book book:new DAO().findByTensach(txtSearch.getText())){
                    model.addRow(new Object[]{
                        book.getMasach(),book.getTensach(),book.getTheloai(),book.getTacgia(),book.getGia()
                    });
                }
                break;
            case "Tác giả":
                model.setRowCount(0);
                for(Book book:new DAO().findByTacgia(txtSearch.getText())){
                    model.addRow(new Object[]{
                        book.getMasach(),book.getTensach(),book.getTheloai(),book.getTacgia(),book.getGia()
                    });
                }
                break;
        }
    }//GEN-LAST:event_txtSearchKeyReleased

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println(" Failed to initialize LaF");
        }
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Theloai;
    private javax.swing.JButton btnNhaplai;
    private javax.swing.JButton btnThem;
    private javax.swing.JComboBox<String> cbxSearch;
    private javax.swing.JComboBox<String> cbxTheloai;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbllist;
    private javax.swing.JTextField txtGia;
    private javax.swing.JTextField txtMasach;
    private javax.swing.JTextField txtNXB;
    private javax.swing.JTextField txtNamXB;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTacgia;
    private javax.swing.JTextField txtTensach;
    // End of variables declaration//GEN-END:variables
}
